In [16]:
import numpy as np
#
#1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1。

In [17]:
a = np.zeros(10)
print(a)
a[4] = 1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
#2. 创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积。

In [19]:
b = np.random.rand(5,3)
c = np.random.rand(3,2)
print(b)
print("-------------")
print(c)
print("------------")
d = np.matmul(b,c)
print(d)



[[0.17816988 0.77248656 0.58042965]
 [0.91224072 0.53573234 0.98532654]
 [0.08079788 0.84430616 0.35957268]
 [0.1806634  0.41086631 0.53407243]
 [0.15833099 0.64258129 0.85477054]]
-------------
[[0.22409629 0.3565029 ]
 [0.88995248 0.52143451]
 [0.17737803 0.63049576]]
------------
[[0.83035901 0.83227766]
 [0.85598137 1.22581   ]
 [0.83327916 0.69576409]
 [0.50087021 0.6153773 ]
 [0.75896572 0.93043872]]


In [20]:
#3. 实现冒泡排序法

In [21]:
a = np.random.rand(int(input("输入序列的长度:")))
print(a)
a = a*10
a = np.fix(a).astype(int)
print(a)
temp = 0
for i in range(0,a.size-1):   
    for j in range(0,a.size-1-i):
        if(a[j]>a[j+1]):  
            temp = a[j]
            a[j] = a[j+1]
            a[j+1] = temp
            a[j],a[j+1] = a[j+1],a[j]
print(a)

输入序列的长度:19
[0.7007069  0.73536266 0.48768733 0.32833096 0.88169468 0.03250383
 0.10122626 0.14106241 0.87786262 0.30084279 0.01680296 0.20336934
 0.21755756 0.5244954  0.98251528 0.71572928 0.86962703 0.87813248
 0.82997343]
[7 7 4 3 8 0 1 1 8 3 0 2 2 5 9 7 8 8 8]
[7 7 4 3 8 0 1 1 8 3 0 2 2 5 9 7 8 8 8]


In [22]:
#4. 找到数组[1,2,0,0,4,0]中0元素的位置索引。

In [23]:
a = [1,2,0,0,4,0]
a = np.array(a)
print(np.where(a==0))


(array([2, 3, 5], dtype=int64),)


In [24]:
#5. 创建一个 10x10 的随机数组并找到它的最大值和最小值 

In [25]:

a = np.random.rand(10,10)*10
a = np.fix(a).astype(int)
print(a)
print('---------------')
print('每行最大值')
print(np.max(a,0))
print('---------------')
print('每列最大值')
print(np.max(a,1))
print('---------------')
print('整个矩阵中的最大值')
print('---------------')
print(np.max(a))

[[8 8 2 9 0 4 0 4 9 7]
 [9 8 8 7 8 6 1 4 3 6]
 [0 9 1 2 3 9 6 6 0 4]
 [1 8 7 3 0 8 6 0 8 1]
 [7 5 3 9 3 7 2 8 8 5]
 [3 1 8 1 9 1 4 5 3 9]
 [0 4 9 6 2 6 2 0 3 6]
 [1 2 3 8 9 3 1 8 1 4]
 [3 5 9 1 5 4 5 6 5 4]
 [6 3 9 7 2 8 8 0 4 4]]
---------------
每行最大值
[9 9 9 9 9 9 8 8 9 9]
---------------
每列最大值
[9 9 9 8 9 9 9 9 9 9]
---------------
整个矩阵中的最大值
---------------
9


In [26]:
#6. 求解方程

In [27]:
a = [[3,3.2],[3.5,3.6]]
b = [[118.4],[135.2]]
a = np.array(a)
a = np.linalg.inv(a)
b = np.array(b)
print(np.matmul(a,b))

[[16.]
 [22.]]
