In [5]:
from numpy import*
a=zeros(10,dtype=int)
print(a)
a[4]=1
print(a)


[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [10]:
a=empty((5,3),dtype=float)
b=empty((3,2),dtype=float)
print(a)
print(b)
print('-'*20)
print(dot(a,b))


[[6.90372910e-310 6.90372910e-310 0.00000000e+000]
 [0.00000000e+000 6.90370111e-310 5.02034658e+175]
 [8.24049932e-067 8.24023882e-067 4.08374196e-033]
 [3.99622524e+175 5.01163106e+217 5.49419094e-143]
 [9.80058441e+252 1.30304358e-142 2.14027814e+161]]
[[6.90372910e-310 4.68039512e-310]
 [0.00000000e+000 0.00000000e+000]
 [6.90370111e-310 5.30276956e+180]]
--------------------
[[0.00000000e+000 0.00000000e+000]
 [3.46589722e-134             inf]
 [0.00000000e+000 2.16551426e+148]
 [2.75888565e-134 2.91344285e+038]
 [6.76605797e-057             inf]]


In [24]:
import random
l=[]
t=[]
for i in range(15):
    l.append(random.randint(0,100))
a=print(l[0:15])
for y in range(6):
    t.append(random.randint(0,100))  
b=print(t[0:6])
del b('')
print(b)
    
    


[34, 0, 7, 20, 54, 26, 27, 30, 97, 56, 3, 10, 36, 30, 59]
[71, 94, 51, 62, 40, 61]
None


In [37]:
a=([
    [4],
    [1],
    [2],
    [7],
    [87],
    [2143],
    [53]
  ])
print(a)
print('pai xu hou')
for i in range(1,len(a)):
    if a[i-1]>a[i]:
        x=a[i-1]
        y=a[i]
        a[i-1]=y
        a[i]=x
    else:
        continue
print(a)    
    

[[4], [1], [2], [7], [87], [2143], [53]]
pai xu hou
[[1], [2], [4], [7], [87], [53], [2143]]


In [40]:
a=arange(10).reshape(2,5)
print(a)
for i in a.flat:
    print(i)
print(list(a.flat))
a.flat[3]

[[0 1 2 3 4]
 [5 6 7 8 9]]
0
1
2
3
4
5
6
7
8
9
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


3

In [111]:
a=([
    [4],
    [1],
    [2],
    [7],
    [87],
    [2143],
    [53]
  ])
print(a)
print('pai xu hou')
'''print(len(a))
for i in range(1,7):
    if a[i-1]>a[i]:
        x=a[i-1]
        y=a[i]
        a[i-1]=y
        a[i]=x
print(a) '''  
for i in range(a):
    for j in range(0,n-i-1):
        if a[j]>a[j+1]:
            a[j],a[j+1]=a[j+1],a[j]
print(a)


[[4], [1], [2], [7], [87], [2143], [53]]
pai xu hou


TypeError: 'list' object cannot be interpreted as an integer

In [52]:
a=([1,2,0,0,4,0])
print(a)
flag=0
for i in a:
    flag+=1
    if i==0:
        print('o place was ',flag)
        

[1, 2, 0, 0, 4, 0]
o place was  3
o place was  4
o place was  6


In [79]:

a=empty([10,10],dtype=int)

for t in range(10):
    for z in range(10):
        i=random.randint(0,100)
        a[t,z]=i
print('*'*20)
print(a)


********************
[[ 86  53  88  56  73  39   3  13  12  86]
 [ 93   5  19  79  56  52  97  19  85 100]
 [ 51  97   5  71  50  82  77  21  34  61]
 [ 47  71  97  77  94  72   1  57  67  44]
 [ 18  60  19  43  52   1  38  88  65  47]
 [ 75  19  64  76  43  99  71  79  55  51]
 [ 66  29   1  44  48  95  75  74  69  21]
 [ 81  31  50  10  77  32  39  75   2  67]
 [ 73   5  39  74  29  39  19  51  24  44]
 [ 87  63  90  96  45  13  57  86  95  99]]


In [101]:
dict={}
class dic():
    #def measage(self,name,phone,emila,place):
        #dict.update((name,phone,emila ,place))
    def delete(self,name):
        del dict[name]
    def serocah(self,name):
        if name in dict:
            return print(dict[name])
        else:
            return print('no find')
d=dic()
print(d.serocah[hs])


NameError: name 'hs' is not defined